version: '3'
services:
  database-dws:
    image: mongo:5.0
    restart: always
    network_mode: "host"  
    volumes: 
      - ./.dws_db:/data/dws_db

  ducatuscore-messagebroker:
    build: .
    restart: always
    image: ducatuscore-messagebroker
    network_mode: "host"
    env_file: .env
    command: 'node ./packages/ducatuscore-wallet-service/ts_build/messagebroker/messagebroker.js'
    
  ducatuscore-emailservice:
    build: .
    restart: always
    image: ducatuscore-emailservice
    network_mode: "host"  
    env_file: .env
    command: 'node ./packages/ducatuscore-wallet-service/ts_build/emailservice/emailservice.js'

  ducatuscore-fiatrateservice:
    build: .
    restart: always
    image: ducatuscore-fiatrateservice
    network_mode: "host"  
    env_file: .env
    command: 'node ./packages/ducatuscore-wallet-service/ts_build/fiatrateservice/fiatrateservice.js'

  ducatuscore-dws:
    build: .
    restart: always
    image: ducatuscore-dws
    volumes: 
      - ./.dws:/data/dws_db
    network_mode: "host"  
    env_file: .env
    command: 'node ./packages/ducatuscore-wallet-service/ts_build/dws.js'

  ducatuscore-pushnotificationsservice:
    build: .
    restart: always
    image: ducatuscore-pushnotificationsservice
    network_mode: "host"  
    env_file: .env
    command: 'node ./packages/ducatuscore-wallet-service/ts_build/pushnotificationsservice/pushnotificationsservice.js'

  ducatuscore-bcmonitor:
    build: .
    restart: always
    image: ducatuscore-bcmonitor
    network_mode: "host"
    env_file: .env
    command: 'node ./packages/ducatuscore-wallet-service/ts_build/bcmonitor/bcmonitor.js'
